<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Api key' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth key' => '',
    'Company name' => '',
    'Create' => '',
    'Create User' => '',
    'Created At' => '',
    'Data' => '',
    'Data has been successfully updated!' => '',
    'Deactivated' => '',
    'Delete' => '',
    'Email' => '',
    'Email has been successfully confirmed!' => '',
    'Forgot Password' => '',
    'Forgot password' => '',
    'ID' => '',
    'Login' => '',
    'Name' => '',
    'OK' => '',
    'Password' => '',
    'Password has been successfully updated!' => '',
    'Password reset code is expired!' => '',
    'Password reset link is sent to your email!' => '',
    'Please fill out the following fields to login:' => '',
    'Register' => '',
    'Remember me' => '',
    'Repeat Password' => '',
    'Reset' => '',
    'Reset Password' => '',
    'Search' => '',
    'Service ID' => '',
    'Set a new password for {email}' => '',
    'Successfully deleted' => '',
    'Successfully saved' => '',
    'Update' => '',
    'Update User: {id}' => '',
    'User #{id}' => '',
    'User ID' => '',
    'User not found' => '',
    'Users' => '',
    'We will send password reset link to this email:' => '',
    'Your authorization link is invalid!' => '',
];
