<?php
/**
 * GeoHelper class file
 */


namespace app\modules\common\helpers;


/**
 * Class GeoHelper
 * @package app\modules\common\helpers
 */
class GeoHelper
{
    const CURRENCY_USD = 'USD';
    const CURRENCY_ILS = 'ILS';

    const LANGUAGE_ENGLISH = 'en';
    const LANGUAGE_HEBREW = 'he';

    const COUNTRY_ISRAEL = "IL";
    const TIMEZONE_ISRAEL = 'Asia/Jerusalem';

    /**
     * @param $model
     * @param string $attribute
     * @return array
     */
    public static function phoneFieldCOnfig($model, $attribute = 'phone')
    {
        $isHebrew = \Yii::$app->language == \app\modules\common\helpers\GeoHelper::LANGUAGE_HEBREW;
        return [
            'mask' =>$isHebrew ? "059{8}" : '(+9{1,3}) 9{4,12}',
            'options' => ['dir' => 'ltr', 'type' => 'tel', 'value' => preg_replace('/^\+?972/', '0', $model->$attribute)]
        ];
    }

    /**
     * @return string
     * @throws \yii\db\Exception
     */
    public static function phonePattern()
    {
        $isHebrew = \Yii::$app->language == \app\modules\common\helpers\GeoHelper::LANGUAGE_HEBREW;
        return $isHebrew ? '/^05(\d{8})$/':'/^\(\+\d+\)[\d\s-]+$/i';
    }

    public static function languageList($return = 'name')
    {
        $result = [
            'ab' =>['name' => 'Abkhaz', 'nativeName' => 'аҧсуа'], 'aa' =>['name' => 'Afar', 'nativeName' => 'Afaraf'],
            'af' =>['name' => 'Afrikaans', 'nativeName' => 'Afrikaans'], 'ak' =>['name' => 'Akan', 'nativeName' => 'Akan'],
            'sq' =>['name' => 'Albanian', 'nativeName' => 'Shqip'], 'am' =>['name' => 'Amharic', 'nativeName' => 'አማርኛ'],
            'ar' =>['name' => 'Arabic', 'nativeName' => 'العربية'], 'an' =>['name' => 'Aragonese', 'nativeName' => 'Aragonés'],
            'hy' =>['name' => 'Armenian', 'nativeName' => 'Հայերեն'], 'as' =>['name' => 'Assamese', 'nativeName' => 'অসমীয়া'],
            'av' =>['name' => 'Avaric', 'nativeName' => 'авар мацӀ, магӀарул мацӀ'], 'ae' =>['name' => 'Avestan', 'nativeName' => 'avesta'],
            'ay' =>['name' => 'Aymara', 'nativeName' => 'aymar aru'], 'az' =>['name' => 'Azerbaijani', 'nativeName' => 'azərbaycan dili'],
            'bm' =>['name' => 'Bambara', 'nativeName' => 'bamanankan'], 'ba' =>['name' => 'Bashkir', 'nativeName' => 'башҡорт теле'],
            'eu' =>['name' => 'Basque', 'nativeName' => 'euskara, euskera'], 'be' =>['name' => 'Belarusian', 'nativeName' => 'Беларуская'],
            'bn' =>['name' => 'Bengali', 'nativeName' => 'বাংলা'], 'bh' =>['name' => 'Bihari', 'nativeName' => 'भोजपुरी'],
            'bi' =>['name' => 'Bislama', 'nativeName' => 'Bislama'], 'bs' =>['name' => 'Bosnian', 'nativeName' => 'bosanski jezik'],
            'br' =>['name' => 'Breton', 'nativeName' => 'brezhoneg'], 'bg' =>['name' => 'Bulgarian', 'nativeName' => 'български език'],
            'my' =>['name' => 'Burmese', 'nativeName' => 'ဗမာစာ'], 'ca' =>['name' => 'Catalan; Valencian', 'nativeName' => 'Català'],
            'ch' =>['name' => 'Chamorro', 'nativeName' => 'Chamoru'], 'ce' =>['name' => 'Chechen', 'nativeName' => 'нохчийн мотт'],
            'ny' =>['name' => 'Chichewa; Chewa; Nyanja', 'nativeName' => 'chiCheŵa, chinyanja'], 'zh' =>['name' => 'Chinese', 'nativeName' => '中文 (Zhōngwén), 汉语, 漢語'],
            'cv' =>['name' => 'Chuvash', 'nativeName' => 'чӑваш чӗлхи'], 'kw' =>['name' => 'Cornish', 'nativeName' => 'Kernewek'],
            'co' =>['name' => 'Corsican', 'nativeName' => 'corsu, lingua corsa'], 'cr' =>['name' => 'Cree', 'nativeName' => 'ᓀᐦᐃᔭᐍᐏᐣ'],
            'hr' =>['name' => 'Croatian', 'nativeName' => 'hrvatski'], 'cs' =>['name' => 'Czech', 'nativeName' => 'česky, čeština'],
            'da' =>['name' => 'Danish', 'nativeName' => 'dansk'], 'dv' =>['name' => 'Divehi; Dhivehi; Maldivian;', 'nativeName' => 'ދިވެހި'],
            'nl' =>['name' => 'Dutch', 'nativeName' => 'Nederlands, Vlaams'], 'en' =>['name' => 'English', 'nativeName' => 'English'],
            'eo' =>['name' => 'Esperanto', 'nativeName' => 'Esperanto'], 'et' =>['name' => 'Estonian', 'nativeName' => 'eesti, eesti keel'],
            'ee' =>['name' => 'Ewe', 'nativeName' => 'Eʋegbe'], 'fo' =>['name' => 'Faroese', 'nativeName' => 'føroyskt'],
            'fj' =>['name' => 'Fijian', 'nativeName' => 'vosa Vakaviti'], 'fi' =>['name' => 'Finnish', 'nativeName' => 'suomi, suomen kieli'],
            'fr' =>['name' => 'French', 'nativeName' => 'français, langue française'], 'ff' =>['name' => 'Fula; Fulah; Pulaar; Pular', 'nativeName' => 'Fulfulde, Pulaar, Pular'],
            'gl' =>['name' => 'Galician', 'nativeName' => 'Galego'], 'ka' =>['name' => 'Georgian', 'nativeName' => 'ქართული'],
            'de' =>['name' => 'German', 'nativeName' => 'Deutsch'], 'el' =>['name' => 'Greek, Modern', 'nativeName' => 'Ελληνικά'],
            'gn' =>['name' => 'Guaraní', 'nativeName' => 'Avañeẽ'], 'gu' =>['name' => 'Gujarati', 'nativeName' => 'ગુજરાતી'],
            'ht' =>['name' => 'Haitian; Haitian Creole', 'nativeName' => 'Kreyòl ayisyen'], 'ha' =>['name' => 'Hausa', 'nativeName' => 'Hausa, هَوُسَ'],
            'he' =>['name' => 'Hebrew', 'nativeName' => 'עברית'],
            'hz' =>['name' => 'Herero', 'nativeName' => 'Otjiherero'],
            'hi' =>['name' => 'Hindi', 'nativeName' => 'हिन्दी, हिंदी'],
            'ho' =>['name' => 'Hiri Motu', 'nativeName' => 'Hiri Motu'], 'hu' =>['name' => 'Hungarian', 'nativeName' => 'Magyar'],
            'ia' =>['name' => 'Interlingua', 'nativeName' => 'Interlingua'], 'id' =>['name' => 'Indonesian', 'nativeName' => 'Bahasa Indonesia'],
            'ie' =>['name' => 'Interlingue', 'nativeName' => 'Originally called Occidental; then Interlingue after WWII'],
            'ga' =>['name' => 'Irish', 'nativeName' => 'Gaeilge'], 'ig' =>['name' => 'Igbo', 'nativeName' => 'Asụsụ Igbo'],
            'ik' =>['name' => 'Inupiaq', 'nativeName' => 'Iñupiaq, Iñupiatun'], 'io' =>['name' => 'Ido', 'nativeName' => 'Ido'],
            'is' =>['name' => 'Icelandic', 'nativeName' => 'Íslenska'], 'it' =>['name' => 'Italian', 'nativeName' => 'Italiano'],
            'iu' =>['name' => 'Inuktitut', 'nativeName' => 'ᐃᓄᒃᑎᑐᑦ'], 'ja' =>['name' => 'Japanese', 'nativeName' => '日本語 (にほんご／にっぽんご)'],
            'jv' =>['name' => 'Javanese', 'nativeName' => 'basa Jawa'], 'kl' =>['name' => 'Kalaallisut, Greenlandic', 'nativeName' => 'kalaallisut, kalaallit oqaasii'],
            'kn' =>['name' => 'Kannada', 'nativeName' => 'ಕನ್ನಡ'], 'kr' =>['name' => 'Kanuri', 'nativeName' => 'Kanuri'],
            'ks' =>['name' => 'Kashmiri', 'nativeName' => 'कश्मीरी, كشميري‎'], 'kk' =>['name' => 'Kazakh', 'nativeName' => 'Қазақ тілі'],
            'km' =>['name' => 'Khmer', 'nativeName' => 'ភាសាខ្មែរ'], 'ki' =>['name' => 'Kikuyu, Gikuyu', 'nativeName' => 'Gĩkũyũ'],
            'rw' =>['name' => 'Kinyarwanda', 'nativeName' => 'Ikinyarwanda'], 'ky' =>['name' => 'Kirghiz, Kyrgyz', 'nativeName' => 'кыргыз тили'],
            'kv' =>['name' => 'Komi', 'nativeName' => 'коми кыв'], 'kg' =>['name' => 'Kongo', 'nativeName' => 'KiKongo'],
            'ko' =>['name' => 'Korean', 'nativeName' => '한국어 (韓國語), 조선말 (朝鮮語)'], 'ku' =>['name' => 'Kurdish', 'nativeName' => 'Kurdî, كوردی‎'],
            'kj' =>['name' => 'Kwanyama, Kuanyama', 'nativeName' => 'Kuanyama'], 'la' =>['name' => 'Latin', 'nativeName' => 'latine, lingua latina'],
            'lb' =>['name' => 'Luxembourgish, Letzeburgesch', 'nativeName' => 'Lëtzebuergesch'], 'lg' =>['name' => 'Luganda', 'nativeName' => 'Luganda'],
            'li' =>['name' => 'Limburgish, Limburgan, Limburger', 'nativeName' => 'Limburgs'], 'ln' =>['name' => 'Lingala', 'nativeName' => 'Lingála'],
            'lo' =>['name' => 'Lao', 'nativeName' => 'ພາສາລາວ'], 'lt' =>['name' => 'Lithuanian', 'nativeName' => 'lietuvių kalba'], '
            lu' =>['name' => 'Luba-Katanga', 'nativeName' => ''], 'lv' =>['name' => 'Latvian', 'nativeName' => 'latviešu valoda'],
            'gv' =>['name' => 'Manx', 'nativeName' => 'Gaelg, Gailck'], 'mk' =>['name' => 'Macedonian', 'nativeName' => 'македонски јазик'],
            'mg' =>['name' => 'Malagasy', 'nativeName' => 'Malagasy fiteny'], 'ms' =>['name' => 'Malay', 'nativeName' => 'bahasa Melayu, بهاس ملايو‎'],
            'ml' =>['name' => 'Malayalam', 'nativeName' => 'മലയാളം'], 'mt' =>['name' => 'Maltese', 'nativeName' => 'Malti'],
            'mi' =>['name' => 'Māori', 'nativeName' => 'te reo Māori'], 'mr' =>['name' => 'Marathi (Marāṭhī)', 'nativeName' => 'मराठी'],
            'mh' =>['name' => 'Marshallese', 'nativeName' => 'Kajin M̧ajeļ'], 'mn' =>['name' => 'Mongolian', 'nativeName' => 'монгол'],
            'na' =>['name' => 'Nauru', 'nativeName' => 'Ekakairũ Naoero'], 'nv' =>['name' => 'Navajo, Navaho', 'nativeName' => 'Diné bizaad, Dinékʼehǰí'],
            'nb' =>['name' => 'Norwegian Bokmål', 'nativeName' => 'Norsk bokmål'], 'nd' =>['name' => 'North Ndebele', 'nativeName' => 'isiNdebele'],
            'ne' =>['name' => 'Nepali', 'nativeName' => 'नेपाली'], 'ng' =>['name' => 'Ndonga', 'nativeName' => 'Owambo'],
            'nn' =>['name' => 'Norwegian Nynorsk', 'nativeName' => 'Norsk nynorsk'], 'no' =>['name' => 'Norwegian', 'nativeName' => 'Norsk'],
            'ii' =>['name' => 'Nuosu', 'nativeName' => 'ꆈꌠ꒿ Nuosuhxop'], 'nr' =>['name' => 'South Ndebele', 'nativeName' => 'isiNdebele'],
            'oc' =>['name' => 'Occitan', 'nativeName' => 'Occitan'], 'oj' =>['name' => 'Ojibwe, Ojibwa', 'nativeName' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ'],
            'cu' =>['name' => 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', 'nativeName' => 'ѩзыкъ словѣньскъ'],
            'om' =>['name' => 'Oromo', 'nativeName' => 'Afaan Oromoo'], 'or' =>['name' => 'Oriya', 'nativeName' => 'ଓଡ଼ିଆ'],
            'os' =>['name' => 'Ossetian, Ossetic', 'nativeName' => 'ирон æвзаг'], 'pa' =>['name' => 'Panjabi, Punjabi', 'nativeName' => 'ਪੰਜਾਬੀ, پنجابی‎'],
            'pi' =>['name' => 'Pāli', 'nativeName' => 'पाऴि'], 'fa' =>['name' => 'Persian', 'nativeName' => 'فارسی'], 'pl' =>['name' => 'Polish', 'nativeName' => 'polski'],
            'ps' =>['name' => 'Pashto, Pushto', 'nativeName' => 'پښتو'], 'pt' =>['name' => 'Portuguese', 'nativeName' => 'Português'],
            'qu' =>['name' => 'Quechua', 'nativeName' => 'Runa Simi, Kichwa'], 'rm' =>['name' => 'Romansh', 'nativeName' => 'rumantsch grischun'],
            'rn' =>['name' => 'Kirundi', 'nativeName' => 'kiRundi'], 'ro' =>['name' => 'Romanian, Moldavian, Moldovan', 'nativeName' => 'română'],
            'ru' =>['name' => 'Russian', 'nativeName' => 'русский язык'], 'sa' =>['name' => 'Sanskrit (Saṁskṛta)', 'nativeName' => 'संस्कृतम्'],
            'sc' =>['name' => 'Sardinian', 'nativeName' => 'sardu'], 'sd' =>['name' => 'Sindhi', 'nativeName' => 'सिन्धी, سنڌي، سندھی‎'],
            'se' =>['name' => 'Northern Sami', 'nativeName' => 'Davvisámegiella'], 'sm' =>['name' => 'Samoan', 'nativeName' => 'gagana faa Samoa'],
            'sg' =>['name' => 'Sango', 'nativeName' => 'yângâ tî sängö'], 'sr' =>['name' => 'Serbian', 'nativeName' => 'српски језик'],
            'gd' =>['name' => 'Scottish Gaelic; Gaelic', 'nativeName' => 'Gàidhlig'], 'sn' =>['name' => 'Shona', 'nativeName' => 'chiShona'],
            'si' =>['name' => 'Sinhala, Sinhalese', 'nativeName' => 'සිංහල'], 'sk' =>['name' => 'Slovak', 'nativeName' => 'slovenčina'],
            'sl' =>['name' => 'Slovene', 'nativeName' => 'slovenščina'], 'so' =>['name' => 'Somali', 'nativeName' => 'Soomaaliga, af Soomaali'],
            'st' =>['name' => 'Southern Sotho', 'nativeName' => 'Sesotho'], 'es' =>['name' => 'Spanish; Castilian', 'nativeName' => 'español, castellano'],
            'su' =>['name' => 'Sundanese', 'nativeName' => 'Basa Sunda'], 'sw' =>['name' => 'Swahili', 'nativeName' => 'Kiswahili'],
            'ss' =>['name' => 'Swati', 'nativeName' => 'SiSwati'], 'sv' =>['name' => 'Swedish', 'nativeName' => 'svenska'],
            'ta' =>['name' => 'Tamil', 'nativeName' => 'தமிழ்'], 'te' =>['name' => 'Telugu', 'nativeName' => 'తెలుగు'],
            'tg' =>['name' => 'Tajik', 'nativeName' => 'тоҷикӣ, toğikī, تاجیکی‎'], 'th' =>['name' => 'Thai', 'nativeName' => 'ไทย'],
            'ti' =>['name' => 'Tigrinya', 'nativeName' => 'ትግርኛ'], 'bo' =>['name' => 'Tibetan Standard, Tibetan, Central', 'nativeName' => 'བོད་ཡིག'],
            'tk' =>['name' => 'Turkmen', 'nativeName' => 'Türkmen, Түркмен'], 'tl' =>['name' => 'Tagalog', 'nativeName' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔'],
            'tn' =>['name' => 'Tswana', 'nativeName' => 'Setswana'], 'to' =>['name' => 'Tonga (Tonga Islands)', 'nativeName' => 'faka Tonga'],
            'tr' =>['name' => 'Turkish', 'nativeName' => 'Türkçe'], 'ts' =>['name' => 'Tsonga', 'nativeName' => 'Xitsonga'],
            'tt' =>['name' => 'Tatar', 'nativeName' => 'татарча, tatarça, تاتارچا‎'], 'tw' =>['name' => 'Twi', 'nativeName' => 'Twi'],
            'ty' =>['name' => 'Tahitian', 'nativeName' => 'Reo Tahiti'], 'ug' =>['name' => 'Uighur, Uyghur', 'nativeName' => 'Uyƣurqə, ئۇيغۇرچە‎'],
            'uk' =>['name' => 'Ukrainian', 'nativeName' => 'українська'], 'ur' =>['name' => 'Urdu', 'nativeName' => 'اردو'],
            'uz' =>['name' => 'Uzbek', 'nativeName' => 'zbek, Ўзбек, أۇزبېك‎'], 've' =>['name' => 'Venda', 'nativeName' => 'Tshivenḓa'],
            'vi' =>['name' => 'Vietnamese', 'nativeName' => 'Tiếng Việt'], 'vo' =>['name' => 'Volapük', 'nativeName' => 'Volapük'],
            'wa' =>['name' => 'Walloon', 'nativeName' => 'Walon'], 'cy' =>['name' => 'Welsh', 'nativeName' => 'Cymraeg'],
            'wo' =>['name' => 'Wolof', 'nativeName' => 'Wollof'], 'fy' =>['name' => 'Western Frisian', 'nativeName' => 'Frysk'],
            'xh' =>['name' => 'Xhosa', 'nativeName' => 'isiXhosa'], 'yi' =>['name' => 'Yiddish', 'nativeName' => 'ייִדיש'],
            'yo' =>['name' => 'Yoruba', 'nativeName' => 'Yorùbá'], 'za' =>['name' => 'Zhuang, Chuang', 'nativeName' => 'Saɯ cueŋƅ, Saw cuengh']
        ];

        return array_map(function ($v) use ($return) { return $return ? $v[$return] : $v; }, $result);
    }

    /**
     * @param string $return
     * @return array
     */
    public static function currencyList($return = 'code')
    {
        $result = [
            'AFN' => ['name' => 'Afghanis', 'symbol' => '؋', 'code' => 'AFN'],
            'ALL' => ['name' => 'Leke', 'symbol' => 'Lek', 'code' => 'ALL'],
            'ANG' => ['name' => 'Guilders', 'symbol' => 'ƒ', 'code' => 'ANG'],
            'ARS' => ['name' => 'Pesos', 'symbol' => '$', 'code' => 'ARS'],
            'AUD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'AUD'],
            'AWG' => ['name' => 'Guilders', 'symbol' => 'ƒ', 'code' => 'AWG'],
            'AZN' => ['name' => 'New Manats', 'symbol' => 'ман', 'code' => 'AZN'],
            'BAM' => ['name' => 'Convertible Marka', 'symbol' => 'KM', 'code' => 'BAM'],
            'BBD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'BBD'],
            'BGN' => ['name' => 'Leva', 'symbol' => 'лв', 'code' => 'BGN'],
            'BMD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'BMD'],
            'BND' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'BND'],
            'BOB' => ['name' => 'Bolivianos', 'symbol' => '$b', 'code' => 'BOB'],
            'BRL' => ['name' => 'Reais', 'symbol' => 'R$', 'code' => 'BRL'],
            'BSD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'BSD'],
            'BWP' => ['name' => 'Pula', 'symbol' => 'P', 'code' => 'BWP'],
            'BYR' => ['name' => 'Rubles', 'symbol' => 'p.', 'code' => 'BYR'],
            'BZD' => ['name' => 'Dollars', 'symbol' => 'BZ$', 'code' => 'BZD'],
            'CAD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'CAD'],
            'CHF' => ['name' => 'Switzerland Francs', 'symbol' => 'CHF', 'code' => 'CHF'],
            'CLP' => ['name' => 'Pesos', 'symbol' => '$', 'code' => 'CLP'],
            'CNY' => ['name' => 'Yuan Renminbi', 'symbol' => '¥', 'code' => 'CNY'],
            'COP' => ['name' => 'Pesos', 'symbol' => '$', 'code' => 'COP'],
            'CRC' => ['name' => 'Colón', 'symbol' => '₡', 'code' => 'CRC'],
            'CUP' => ['name' => 'Pesos', 'symbol' => '₱', 'code' => 'CUP'],
            'CZK' => ['name' => 'Koruny', 'symbol' => 'Kč', 'code' => 'CZK'],
            'DKK' => ['name' => 'Kroner', 'symbol' => 'kr', 'code' => 'DKK'],
            'DOP ' => ['name' => 'Pesos', 'symbol' => 'RD$', 'code' => 'DOP '],
            'EGP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'EGP'],
            'EUR' => ['name' => 'Euro', 'symbol' => '€', 'code' => 'EUR'],
            'FJD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'FJD'],
            'FKP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'FKP'],
            'GBP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'GBP'],
            'GGP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'GGP'],
            'GHC' => ['name' => 'Cedis', 'symbol' => '¢', 'code' => 'GHC'],
            'GIP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'GIP'],
            'GTQ' => ['name' => 'Quetzales', 'symbol' => 'Q', 'code' => 'GTQ'],
            'GYD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'GYD'],
            'HKD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'HKD'],
            'HNL' => ['name' => 'Lempiras', 'symbol' => 'L', 'code' => 'HNL'],
            'HRK' => ['name' => 'Kuna', 'symbol' => 'kn', 'code' => 'HRK'],
            'HUF' => ['name' => 'Forint', 'symbol' => 'Ft', 'code' => 'HUF'],
            'IDR' => ['name' => 'Rupiahs', 'symbol' => 'Rp', 'code' => 'IDR'],
            'ILS' => ['name' => 'New Shekels', 'symbol' => '₪', 'code' => 'ILS'],
            'IMP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'IMP'],
            'INR' => ['name' => 'Rupees', 'symbol' => 'Rp', 'code' => 'INR'],
            'IRR' => ['name' => 'Rials', 'symbol' => '﷼', 'code' => 'IRR'],
            'ISK' => ['name' => 'Kronur', 'symbol' => 'kr', 'code' => 'ISK'],
            'JEP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'JEP'],
            'JMD' => ['name' => 'Dollars', 'symbol' => 'J$', 'code' => 'JMD'],
            'JPY' => ['name' => 'Yen', 'symbol' => '¥', 'code' => 'JPY'],
            'KGS' => ['name' => 'Soms', 'symbol' => 'лв', 'code' => 'KGS'],
            'KHR' => ['name' => 'Riels', 'symbol' => '៛', 'code' => 'KHR'],
            'KPW' => ['name' => 'Won', 'symbol' => '₩', 'code' => 'KPW'],
            'KRW' => ['name' => 'Won', 'symbol' => '₩', 'code' => 'KRW'],
            'KYD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'KYD'],
            'KZT' => ['name' => 'Tenge', 'symbol' => 'лв', 'code' => 'KZT'],
            'LAK' => ['name' => 'Kips', 'symbol' => '₭', 'code' => 'LAK'],
            'LBP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'LBP'],
            'LKR' => ['name' => 'Rupees', 'symbol' => '₨', 'code' => 'LKR'],
            'LRD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'LRD'],
            'LTL' => ['name' => 'Litai', 'symbol' => 'Lt', 'code' => 'LTL'],
            'LVL' => ['name' => 'Lati', 'symbol' => 'Ls', 'code' => 'LVL'],
            'MKD' => ['name' => 'Denars', 'symbol' => 'ден', 'code' => 'MKD'],
            'MNT' => ['name' => 'Tugriks', 'symbol' => '₮', 'code' => 'MNT'],
            'MUR' => ['name' => 'Rupees', 'symbol' => '₨', 'code' => 'MUR'],
            'MXN' => ['name' => 'Pesos', 'symbol' => '$', 'code' => 'MXN'],
            'MYR' => ['name' => 'Ringgits', 'symbol' => 'RM', 'code' => 'MYR'],
            'MZN' => ['name' => 'Meticais', 'symbol' => 'MT', 'code' => 'MZN'],
            'NAD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'NAD'],
            'NGN' => ['name' => 'Nairas', 'symbol' => '₦', 'code' => 'NGN'],
            'NIO' => ['name' => 'Cordobas', 'symbol' => 'C$', 'code' => 'NIO'],
            'NOK' => ['name' => 'Krone', 'symbol' => 'kr', 'code' => 'NOK'],
            'NPR' => ['name' => 'Rupees', 'symbol' => '₨', 'code' => 'NPR'],
            'NZD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'NZD'],
            'OMR' => ['name' => 'Rials', 'symbol' => '﷼', 'code' => 'OMR'],
            'PAB' => ['name' => 'Balboa', 'symbol' => 'B/.', 'code' => 'PAB'],
            'PEN' => ['name' => 'Nuevos Soles', 'symbol' => 'S/.', 'code' => 'PEN'],
            'PHP' => ['name' => 'Pesos', 'symbol' => 'Php', 'code' => 'PHP'],
            'PKR' => ['name' => 'Rupees', 'symbol' => '₨', 'code' => 'PKR'],
            'PLN' => ['name' => 'Zlotych', 'symbol' => 'zł', 'code' => 'PLN'],
            'PYG' => ['name' => 'Guarani', 'symbol' => 'Gs', 'code' => 'PYG'],
            'QAR' => ['name' => 'Rials', 'symbol' => '﷼', 'code' => 'QAR'],
            'RON' => ['name' => 'New Lei', 'symbol' => 'lei', 'code' => 'RON'],
            'RSD' => ['name' => 'Dinars', 'symbol' => 'Дин.', 'code' => 'RSD'],
            'RUB' => ['name' => 'Rubles', 'symbol' => 'руб', 'code' => 'RUB'],
            'SAR' => ['name' => 'Riyals', 'symbol' => '﷼', 'code' => 'SAR'],
            'SBD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'SBD'],
            'SCR' => ['name' => 'Rupees', 'symbol' => '₨', 'code' => 'SCR'],
            'SEK' => ['name' => 'Kronor', 'symbol' => 'kr', 'code' => 'SEK'],
            'SGD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'SGD'],
            'SHP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'SHP'],
            'SOS' => ['name' => 'Shillings', 'symbol' => 'S', 'code' => 'SOS'],
            'SRD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'SRD'],
            'SVC' => ['name' => 'Colones', 'symbol' => '$', 'code' => 'SVC'],
            'SYP' => ['name' => 'Pounds', 'symbol' => '£', 'code' => 'SYP'],
            'THB' => ['name' => 'Baht', 'symbol' => '฿', 'code' => 'THB'],
            'TRL' => ['name' => 'Liras', 'symbol' => '£', 'code' => 'TRL'],
            'TRY' => ['name' => 'Lira', 'symbol' => 'TL', 'code' => 'TRY'],
            'TTD' => ['name' => 'Dollars', 'symbol' => 'TT$', 'code' => 'TTD'],
            'TVD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'TVD'],
            'TWD' => ['name' => 'New Dollars', 'symbol' => 'NT$', 'code' => 'TWD'],
            'UAH' => ['name' => 'Hryvnia', 'symbol' => '₴', 'code' => 'UAH'],
            'USD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'USD'],
            'UYU' => ['name' => 'Pesos', 'symbol' => '$U', 'code' => 'UYU'],
            'UZS' => ['name' => 'Sums', 'symbol' => 'лв', 'code' => 'UZS'],
            'VEF' => ['name' => 'Bolivares Fuertes', 'symbol' => 'Bs', 'code' => 'VEF'],
            'VND' => ['name' => 'Dong', 'symbol' => '₫', 'code' => 'VND'],
            'XCD' => ['name' => 'Dollars', 'symbol' => '$', 'code' => 'XCD'],
            'YER' => ['name' => 'Rials', 'symbol' => '﷼', 'code' => 'YER'],
            'ZAR' => ['name' => 'Rand', 'symbol' => 'R', 'code' => 'ZAR'],
            'ZWD' => ['name' => 'Zimbabwe Dollars', 'symbol' => 'Z$', 'code' => 'ZWD'],
        ];
        $first = HtmlHelper::isRtl() ? ['ILS', 'USD', 'EUR'] : ['USD', 'ILS', 'EUR'];
        $result = array_replace(array_flip($first), $result); // place popular currencies first
        return array_map(function ($v) use ($return) { return $v[$return] ?? $v; }, $result);
    }

    /**
     * @param $value
     * @param $currency
     * @return string
     */
    public static function asCurrency($value, $currency)
    {
        return preg_replace('/[A-z]/', '', \Yii::$app->formatter->asCurrency($value, $currency,  [ // remove 'USD' name and .00
            \NumberFormatter::MIN_FRACTION_DIGITS => 0,
            \NumberFormatter::MAX_FRACTION_DIGITS => 0,
        ]));
    }

    /**
     * @return array
     */
    public static function timezoneList()
    {
        $result = [
            'Africa/Abidjan' => 'CI',
            'Africa/Accra' => 'GH',
            'Africa/Addis_Ababa' => 'ET',
            'Africa/Algiers' => 'DZ',
            'Africa/Asmara' => 'ER',
            'Africa/Bamako' => 'ML',
            'Africa/Bangui' => 'CF',
            'Africa/Banjul' => 'GM',
            'Africa/Bissau' => 'GW',
            'Africa/Blantyre' => 'MW',
            'Africa/Brazzaville' => 'CG',
            'Africa/Bujumbura' => 'BI',
            'Africa/Cairo' => 'EG',
            'Africa/Casablanca' => 'MA',
            'Africa/Ceuta' => 'ES',
            'Africa/Conakry' => 'GN',
            'Africa/Dakar' => 'SN',
            'Africa/Dar_es_Salaam' => 'TZ',
            'Africa/Djibouti' => 'DJ',
            'Africa/Douala' => 'CM',
            'Africa/El_Aaiun' => 'EH',
            'Africa/Freetown' => 'SL',
            'Africa/Gaborone' => 'BW',
            'Africa/Harare' => 'ZW',
            'Africa/Johannesburg' => 'ZA',
            'Africa/Juba' => 'SS',
            'Africa/Kampala' => 'UG',
            'Africa/Khartoum' => 'SD',
            'Africa/Kigali' => 'RW',
            'Africa/Kinshasa' => 'CD',
            'Africa/Lagos' => 'NG',
            'Africa/Libreville' => 'GA',
            'Africa/Lome' => 'TG',
            'Africa/Luanda' => 'AO',
            'Africa/Lubumbashi' => 'CD',
            'Africa/Lusaka' => 'ZM',
            'Africa/Malabo' => 'GQ',
            'Africa/Maputo' => 'MZ',
            'Africa/Maseru' => 'LS',
            'Africa/Mbabane' => 'SZ',
            'Africa/Mogadishu' => 'SO',
            'Africa/Monrovia' => 'LR',
            'Africa/Nairobi' => 'KE',
            'Africa/Ndjamena' => 'TD',
            'Africa/Niamey' => 'NE',
            'Africa/Nouakchott' => 'MR',
            'Africa/Ouagadougou' => 'BF',
            'Africa/Porto-Novo' => 'BJ',
            'Africa/Sao_Tome' => 'ST',
            'Africa/Tripoli' => 'LY',
            'Africa/Tunis' => 'TN',
            'Africa/Windhoek' => 'NA',
            'America/Adak' => 'US',
            'America/Anchorage' => 'US',
            'America/Anguilla' => 'AI',
            'America/Antigua' => 'AG',
            'America/Araguaina' => 'BR',
            'America/Argentina/Buenos_Aires' => 'AR',
            'America/Argentina/Catamarca' => 'AR',
            'America/Argentina/Cordoba' => 'AR',
            'America/Argentina/Jujuy' => 'AR',
            'America/Argentina/La_Rioja' => 'AR',
            'America/Argentina/Mendoza' => 'AR',
            'America/Argentina/Rio_Gallegos' => 'AR',
            'America/Argentina/Salta' => 'AR',
            'America/Argentina/San_Juan' => 'AR',
            'America/Argentina/San_Luis' => 'AR',
            'America/Argentina/Tucuman' => 'AR',
            'America/Argentina/Ushuaia' => 'AR',
            'America/Aruba' => 'AW',
            'America/Asuncion' => 'PY',
            'America/Atikokan' => 'CA',
            'America/Bahia' => 'BR',
            'America/Bahia_Banderas' => 'MX',
            'America/Barbados' => 'BB',
            'America/Belem' => 'BR',
            'America/Belize' => 'BZ',
            'America/Blanc-Sablon' => 'CA',
            'America/Boa_Vista' => 'BR',
            'America/Bogota' => 'CO',
            'America/Boise' => 'US',
            'America/Cambridge_Bay' => 'CA',
            'America/Campo_Grande' => 'BR',
            'America/Cancun' => 'MX',
            'America/Caracas' => 'VE',
            'America/Cayenne' => 'GF',
            'America/Cayman' => 'KY',
            'America/Chicago' => 'US',
            'America/Chihuahua' => 'MX',
            'America/Costa_Rica' => 'CR',
            'America/Creston' => 'CA',
            'America/Cuiaba' => 'BR',
            'America/Curacao' => 'CW',
            'America/Danmarkshavn' => 'GL',
            'America/Dawson' => 'CA',
            'America/Dawson_Creek' => 'CA',
            'America/Denver' => 'US',
            'America/Detroit' => 'US',
            'America/Dominica' => 'DM',
            'America/Edmonton' => 'CA',
            'America/Eirunepe' => 'BR',
            'America/El_Salvador' => 'SV',
            'America/Fort_Nelson' => 'CA',
            'America/Fortaleza' => 'BR',
            'America/Glace_Bay' => 'CA',
            'America/Godthab' => 'GL',
            'America/Goose_Bay' => 'CA',
            'America/Grand_Turk' => 'TC',
            'America/Grenada' => 'GD',
            'America/Guadeloupe' => 'GP',
            'America/Guatemala' => 'GT',
            'America/Guayaquil' => 'EC',
            'America/Guyana' => 'GY',
            'America/Halifax' => 'CA',
            'America/Havana' => 'CU',
            'America/Hermosillo' => 'MX',
            'America/Indiana/Indianapolis' => 'US',
            'America/Indiana/Knox' => 'US',
            'America/Indiana/Marengo' => 'US',
            'America/Indiana/Petersburg' => 'US',
            'America/Indiana/Tell_City' => 'US',
            'America/Indiana/Vevay' => 'US',
            'America/Indiana/Vincennes' => 'US',
            'America/Indiana/Winamac' => 'US',
            'America/Inuvik' => 'CA',
            'America/Iqaluit' => 'CA',
            'America/Jamaica' => 'JM',
            'America/Juneau' => 'US',
            'America/Kentucky/Louisville' => 'US',
            'America/Kentucky/Monticello' => 'US',
            'America/Kralendijk' => 'BQ',
            'America/La_Paz' => 'BO',
            'America/Lima' => 'PE',
            'America/Los_Angeles' => 'US',
            'America/Lower_Princes' => 'SX',
            'America/Maceio' => 'BR',
            'America/Managua' => 'NI',
            'America/Manaus' => 'BR',
            'America/Marigot' => 'MF',
            'America/Martinique' => 'MQ',
            'America/Matamoros' => 'MX',
            'America/Mazatlan' => 'MX',
            'America/Menominee' => 'US',
            'America/Merida' => 'MX',
            'America/Metlakatla' => 'US',
            'America/Mexico_City' => 'MX',
            'America/Miquelon' => 'PM',
            'America/Moncton' => 'CA',
            'America/Monterrey' => 'MX',
            'America/Montevideo' => 'UY',
            'America/Montserrat' => 'MS',
            'America/Nassau' => 'BS',
            'America/New_York' => 'US',
            'America/Nipigon' => 'CA',
            'America/Nome' => 'US',
            'America/Noronha' => 'BR',
            'America/North_Dakota/Beulah' => 'US',
            'America/North_Dakota/Center' => 'US',
            'America/North_Dakota/New_Salem' => 'US',
            'America/Ojinaga' => 'MX',
            'America/Panama' => 'PA',
            'America/Pangnirtung' => 'CA',
            'America/Paramaribo' => 'SR',
            'America/Phoenix' => 'US',
            'America/Port-au-Prince' => 'HT',
            'America/Port_of_Spain' => 'TT',
            'America/Porto_Velho' => 'BR',
            'America/Puerto_Rico' => 'PR',
            'America/Punta_Arenas' => 'CL',
            'America/Rainy_River' => 'CA',
            'America/Rankin_Inlet' => 'CA',
            'America/Recife' => 'BR',
            'America/Regina' => 'CA',
            'America/Resolute' => 'CA',
            'America/Rio_Branco' => 'BR',
            'America/Santarem' => 'BR',
            'America/Santiago' => 'CL',
            'America/Santo_Domingo' => 'DO',
            'America/Sao_Paulo' => 'BR',
            'America/Scoresbysund' => 'GL',
            'America/Sitka' => 'US',
            'America/St_Barthelemy' => 'BL',
            'America/St_Johns' => 'CA',
            'America/St_Kitts' => 'KN',
            'America/St_Lucia' => 'LC',
            'America/St_Thomas' => 'VI',
            'America/St_Vincent' => 'VC',
            'America/Swift_Current' => 'CA',
            'America/Tegucigalpa' => 'HN',
            'America/Thule' => 'GL',
            'America/Thunder_Bay' => 'CA',
            'America/Tijuana' => 'MX',
            'America/Toronto' => 'CA',
            'America/Tortola' => 'VG',
            'America/Vancouver' => 'CA',
            'America/Whitehorse' => 'CA',
            'America/Winnipeg' => 'CA',
            'America/Yakutat' => 'US',
            'America/Yellowknife' => 'CA',
            'Antarctica/Casey' => 'AQ',
            'Antarctica/Davis' => 'AQ',
            'Antarctica/DumontDUrville' => 'AQ',
            'Antarctica/Macquarie' => 'AU',
            'Antarctica/Mawson' => 'AQ',
            'Antarctica/McMurdo' => 'AQ',
            'Antarctica/Palmer' => 'AQ',
            'Antarctica/Rothera' => 'AQ',
            'Antarctica/Syowa' => 'AQ',
            'Antarctica/Troll' => 'AQ',
            'Antarctica/Vostok' => 'AQ',
            'Arctic/Longyearbyen' => 'SJ',
            'Asia/Aden' => 'YE',
            'Asia/Almaty' => 'KZ',
            'Asia/Amman' => 'JO',
            'Asia/Anadyr' => 'RU',
            'Asia/Aqtau' => 'KZ',
            'Asia/Aqtobe' => 'KZ',
            'Asia/Ashgabat' => 'TM',
            'Asia/Atyrau' => 'KZ',
            'Asia/Baghdad' => 'IQ',
            'Asia/Bahrain' => 'BH',
            'Asia/Baku' => 'AZ',
            'Asia/Bangkok' => 'TH',
            'Asia/Barnaul' => 'RU',
            'Asia/Beirut' => 'LB',
            'Asia/Bishkek' => 'KG',
            'Asia/Brunei' => 'BN',
            'Asia/Chita' => 'RU',
            'Asia/Choibalsan' => 'MN',
            'Asia/Colombo' => 'LK',
            'Asia/Damascus' => 'SY',
            'Asia/Dhaka' => 'BD',
            'Asia/Dili' => 'TL',
            'Asia/Dubai' => 'AE',
            'Asia/Dushanbe' => 'TJ',
            'Asia/Famagusta' => 'CY',
            'Asia/Gaza' => 'PS',
            'Asia/Hebron' => 'PS',
            'Asia/Ho_Chi_Minh' => 'VN',
            'Asia/Hong_Kong' => 'HK',
            'Asia/Hovd' => 'MN',
            'Asia/Irkutsk' => 'RU',
            'Asia/Jakarta' => 'ID',
            'Asia/Jayapura' => 'ID',
            'Asia/Jerusalem' => 'IL',
            'Asia/Kabul' => 'AF',
            'Asia/Kamchatka' => 'RU',
            'Asia/Karachi' => 'PK',
            'Asia/Kathmandu' => 'NP',
            'Asia/Khandyga' => 'RU',
            'Asia/Kolkata' => 'IN',
            'Asia/Krasnoyarsk' => 'RU',
            'Asia/Kuala_Lumpur' => 'MY',
            'Asia/Kuching' => 'MY',
            'Asia/Kuwait' => 'KW',
            'Asia/Macau' => 'MO',
            'Asia/Magadan' => 'RU',
            'Asia/Makassar' => 'ID',
            'Asia/Manila' => 'PH',
            'Asia/Muscat' => 'OM',
            'Asia/Nicosia' => 'CY',
            'Asia/Novokuznetsk' => 'RU',
            'Asia/Novosibirsk' => 'RU',
            'Asia/Omsk' => 'RU',
            'Asia/Oral' => 'KZ',
            'Asia/Phnom_Penh' => 'KH',
            'Asia/Pontianak' => 'ID',
            'Asia/Pyongyang' => 'KP',
            'Asia/Qatar' => 'QA',
            'Asia/Qostanay' => 'KZ',
            'Asia/Qyzylorda' => 'KZ',
            'Asia/Riyadh' => 'SA',
            'Asia/Sakhalin' => 'RU',
            'Asia/Samarkand' => 'UZ',
            'Asia/Seoul' => 'KR',
            'Asia/Shanghai' => 'CN',
            'Asia/Singapore' => 'SG',
            'Asia/Srednekolymsk' => 'RU',
            'Asia/Taipei' => 'TW',
            'Asia/Tashkent' => 'UZ',
            'Asia/Tbilisi' => 'GE',
            'Asia/Tehran' => 'IR',
            'Asia/Thimphu' => 'BT',
            'Asia/Tokyo' => 'JP',
            'Asia/Tomsk' => 'RU',
            'Asia/Ulaanbaatar' => 'MN',
            'Asia/Urumqi' => 'CN',
            'Asia/Ust-Nera' => 'RU',
            'Asia/Vientiane' => 'LA',
            'Asia/Vladivostok' => 'RU',
            'Asia/Yakutsk' => 'RU',
            'Asia/Yangon' => 'MM',
            'Asia/Yekaterinburg' => 'RU',
            'Asia/Yerevan' => 'AM',
            'Atlantic/Azores' => 'PT',
            'Atlantic/Bermuda' => 'BM',
            'Atlantic/Canary' => 'ES',
            'Atlantic/Cape_Verde' => 'CV',
            'Atlantic/Faroe' => 'FO',
            'Atlantic/Madeira' => 'PT',
            'Atlantic/Reykjavik' => 'IS',
            'Atlantic/South_Georgia' => 'GS',
            'Atlantic/St_Helena' => 'SH',
            'Atlantic/Stanley' => 'FK',
            'Australia/Adelaide' => 'AU',
            'Australia/Brisbane' => 'AU',
            'Australia/Broken_Hill' => 'AU',
            'Australia/Currie' => 'AU',
            'Australia/Darwin' => 'AU',
            'Australia/Eucla' => 'AU',
            'Australia/Hobart' => 'AU',
            'Australia/Lindeman' => 'AU',
            'Australia/Lord_Howe' => 'AU',
            'Australia/Melbourne' => 'AU',
            'Australia/Perth' => 'AU',
            'Australia/Sydney' => 'AU',
            'Europe/Amsterdam' => 'NL',
            'Europe/Andorra' => 'AD',
            'Europe/Astrakhan' => 'RU',
            'Europe/Athens' => 'GR',
            'Europe/Belgrade' => 'RS',
            'Europe/Berlin' => 'DE',
            'Europe/Bratislava' => 'SK',
            'Europe/Brussels' => 'BE',
            'Europe/Bucharest' => 'RO',
            'Europe/Budapest' => 'HU',
            'Europe/Busingen' => 'DE',
            'Europe/Chisinau' => 'MD',
            'Europe/Copenhagen' => 'DK',
            'Europe/Dublin' => 'IE',
            'Europe/Gibraltar' => 'GI',
            'Europe/Guernsey' => 'GG',
            'Europe/Helsinki' => 'FI',
            'Europe/Isle_of_Man' => 'IM',
            'Europe/Istanbul' => 'TR',
            'Europe/Jersey' => 'JE',
            'Europe/Kaliningrad' => 'RU',
            'Europe/Kiev' => 'UA',
            'Europe/Kirov' => 'RU',
            'Europe/Lisbon' => 'PT',
            'Europe/Ljubljana' => 'SI',
            'Europe/London' => 'GB',
            'Europe/Luxembourg' => 'LU',
            'Europe/Madrid' => 'ES',
            'Europe/Malta' => 'MT',
            'Europe/Mariehamn' => 'AX',
            'Europe/Minsk' => 'BY',
            'Europe/Monaco' => 'MC',
            'Europe/Moscow' => 'RU',
            'Europe/Oslo' => 'NO',
            'Europe/Paris' => 'FR',
            'Europe/Podgorica' => 'ME',
            'Europe/Prague' => 'CZ',
            'Europe/Riga' => 'LV',
            'Europe/Rome' => 'IT',
            'Europe/Samara' => 'RU',
            'Europe/San_Marino' => 'SM',
            'Europe/Sarajevo' => 'BA',
            'Europe/Saratov' => 'RU',
            'Europe/Simferopol' => 'UA',
            'Europe/Skopje' => 'MK',
            'Europe/Sofia' => 'BG',
            'Europe/Stockholm' => 'SE',
            'Europe/Tallinn' => 'EE',
            'Europe/Tirane' => 'AL',
            'Europe/Ulyanovsk' => 'RU',
            'Europe/Uzhgorod' => 'UA',
            'Europe/Vaduz' => 'LI',
            'Europe/Vatican' => 'VA',
            'Europe/Vienna' => 'AT',
            'Europe/Vilnius' => 'LT',
            'Europe/Volgograd' => 'RU',
            'Europe/Warsaw' => 'PL',
            'Europe/Zagreb' => 'HR',
            'Europe/Zaporozhye' => 'UA',
            'Europe/Zurich' => 'CH',
            'Indian/Antananarivo' => 'MG',
            'Indian/Chagos' => 'IO',
            'Indian/Christmas' => 'CX',
            'Indian/Cocos' => 'CC',
            'Indian/Comoro' => 'KM',
            'Indian/Kerguelen' => 'TF',
            'Indian/Mahe' => 'SC',
            'Indian/Maldives' => 'MV',
            'Indian/Mauritius' => 'MU',
            'Indian/Mayotte' => 'YT',
            'Indian/Reunion' => 'RE',
            'Pacific/Apia' => 'WS',
            'Pacific/Auckland' => 'NZ',
            'Pacific/Bougainville' => 'PG',
            'Pacific/Chatham' => 'NZ',
            'Pacific/Chuuk' => 'FM',
            'Pacific/Easter' => 'CL',
            'Pacific/Efate' => 'VU',
            'Pacific/Enderbury' => 'KI',
            'Pacific/Fakaofo' => 'TK',
            'Pacific/Fiji' => 'FJ',
            'Pacific/Funafuti' => 'TV',
            'Pacific/Galapagos' => 'EC',
            'Pacific/Gambier' => 'PF',
            'Pacific/Guadalcanal' => 'SB',
            'Pacific/Guam' => 'GU',
            'Pacific/Honolulu' => 'US',
            'Pacific/Kiritimati' => 'KI',
            'Pacific/Kosrae' => 'FM',
            'Pacific/Kwajalein' => 'MH',
            'Pacific/Majuro' => 'MH',
            'Pacific/Marquesas' => 'PF',
            'Pacific/Midway' => 'UM',
            'Pacific/Nauru' => 'NR',
            'Pacific/Niue' => 'NU',
            'Pacific/Norfolk' => 'NF',
            'Pacific/Noumea' => 'NC',
            'Pacific/Pago_Pago' => 'AS',
            'Pacific/Palau' => 'PW',
            'Pacific/Pitcairn' => 'PN',
            'Pacific/Pohnpei' => 'FM',
            'Pacific/Port_Moresby' => 'PG',
            'Pacific/Rarotonga' => 'CK',
            'Pacific/Saipan' => 'MP',
            'Pacific/Tahiti' => 'PF',
            'Pacific/Tarawa' => 'KI',
            'Pacific/Tongatapu' => 'TO',
            'Pacific/Wake' => 'UM',
            'Pacific/Wallis' => 'WF',
        ];
        return array_combine(array_keys($result), array_keys($result));
    }

    public static function countryList($return = 'name')
    {
        $result = [
            'AF' => ['name' => 'Afghanistan', 'phonecode' => '93'],
            'AL' => ['name' => 'Albania', 'phonecode' => '355'],
            'DZ' => ['name' => 'Algeria', 'phonecode' => '213'],
            'AD' => ['name' => 'Andorra', 'phonecode' => '376'],
            'AO' => ['name' => 'Angola', 'phonecode' => '244'],
            'AI' => ['name' => 'Anguilla', 'phonecode' => '1264'],
            'AQ' => ['name' => 'Antarctica', 'phonecode' => '0'],
            'AG' => ['name' => 'Antigua And Barbuda', 'phonecode' => '1268'],
            'AR' => ['name' => 'Argentina', 'phonecode' => '54'],
            'AM' => ['name' => 'Armenia', 'phonecode' => '374'],
            'AW' => ['name' => 'Aruba', 'phonecode' => '297'],
            'AU' => ['name' => 'Australia', 'phonecode' => '61'],
            'AT' => ['name' => 'Austria', 'phonecode' => '43'],
            'AZ' => ['name' => 'Azerbaijan', 'phonecode' => '994'],
            'BH' => ['name' => 'Bahrain', 'phonecode' => '973'],
            'BD' => ['name' => 'Bangladesh', 'phonecode' => '880'],
            'BB' => ['name' => 'Barbados', 'phonecode' => '1246'],
            'BY' => ['name' => 'Belarus', 'phonecode' => '375'],
            'BE' => ['name' => 'Belgium', 'phonecode' => '32'],
            'BZ' => ['name' => 'Belize', 'phonecode' => '501'],
            'BJ' => ['name' => 'Benin', 'phonecode' => '229'],
            'BM' => ['name' => 'Bermuda', 'phonecode' => '1441'],
            'BT' => ['name' => 'Bhutan', 'phonecode' => '975'],
            'BO' => ['name' => 'Bolivia', 'phonecode' => '591'],
            'BA' => ['name' => 'Bosnia And Herzegovina', 'phonecode' => '387'],
            'BW' => ['name' => 'Botswana', 'phonecode' => '267'],
            'BR' => ['name' => 'Brazil', 'phonecode' => '55'],
            'BG' => ['name' => 'Bulgaria', 'phonecode' => '359'],
            'BF' => ['name' => 'Burkina Faso', 'phonecode' => '226'],
            'BI' => ['name' => 'Burundi', 'phonecode' => '257'],
            'KH' => ['name' => 'Cambodia', 'phonecode' => '855'],
            'CM' => ['name' => 'Cameroon', 'phonecode' => '237'],
            'CA' => ['name' => 'Canada', 'phonecode' => '1'],
            'CV' => ['name' => 'Cape Verde', 'phonecode' => '238'],
            'KY' => ['name' => 'Cayman Islands', 'phonecode' => '1345'],
            'CF' => ['name' => 'Central African Republic', 'phonecode' => '236'],
            'TD' => ['name' => 'Chad', 'phonecode' => '235'],
            'CL' => ['name' => 'Chile', 'phonecode' => '56'],
            'CN' => ['name' => 'China', 'phonecode' => '86'],
            'CX' => ['name' => 'Christmas Island', 'phonecode' => '61'],
            'CO' => ['name' => 'Colombia', 'phonecode' => '57'],
            'KM' => ['name' => 'Comoros', 'phonecode' => '269'],
            'CK' => ['name' => 'Cook Islands', 'phonecode' => '682'],
            'CR' => ['name' => 'Costa Rica', 'phonecode' => '506'],
            'HR' => ['name' => 'Croatia', 'phonecode' => '385'],
            'CU' => ['name' => 'Cuba', 'phonecode' => '53'],
            'CY' => ['name' => 'Cyprus', 'phonecode' => '357'],
            'CZ' => ['name' => 'Czech Republic', 'phonecode' => '420'],
            'DK' => ['name' => 'Denmark', 'phonecode' => '45'],
            'DJ' => ['name' => 'Djibouti', 'phonecode' => '253'],
            'DM' => ['name' => 'Dominica', 'phonecode' => '1767'],
            'DO' => ['name' => 'Dominican Republic', 'phonecode' => '1809'],
            'EC' => ['name' => 'Ecuador', 'phonecode' => '593'],
            'EG' => ['name' => 'Egypt', 'phonecode' => '20'],
            'SV' => ['name' => 'El Salvador', 'phonecode' => '503'],
            'GQ' => ['name' => 'Equatorial Guinea', 'phonecode' => '240'],
            'ER' => ['name' => 'Eritrea', 'phonecode' => '291'],
            'EE' => ['name' => 'Estonia', 'phonecode' => '372'],
            'ET' => ['name' => 'Ethiopia', 'phonecode' => '251'],
            'FJ' => ['name' => 'Fiji', 'phonecode' => '679'],
            'FI' => ['name' => 'Finland', 'phonecode' => '358'],
            'FR' => ['name' => 'France', 'phonecode' => '33'],
            'GF' => ['name' => 'French Guiana', 'phonecode' => '594'],
            'PF' => ['name' => 'French Polynesia', 'phonecode' => '689'],
            'GA' => ['name' => 'Gabon', 'phonecode' => '241'],
            'GE' => ['name' => 'Georgia', 'phonecode' => '995'],
            'DE' => ['name' => 'Germany', 'phonecode' => '49'],
            'GH' => ['name' => 'Ghana', 'phonecode' => '233'],
            'GI' => ['name' => 'Gibraltar', 'phonecode' => '350'],
            'GR' => ['name' => 'Greece', 'phonecode' => '30'],
            'GL' => ['name' => 'Greenland', 'phonecode' => '299'],
            'GD' => ['name' => 'Grenada', 'phonecode' => '1473'],
            'GP' => ['name' => 'Guadeloupe', 'phonecode' => '590'],
            'GT' => ['name' => 'Guatemala', 'phonecode' => '502'],
            'GN' => ['name' => 'Guinea', 'phonecode' => '224'],
            'GW' => ['name' => 'Guinea-bissau', 'phonecode' => '245'],
            'GY' => ['name' => 'Guyana', 'phonecode' => '592'],
            'HT' => ['name' => 'Haiti', 'phonecode' => '509'],
            'HN' => ['name' => 'Honduras', 'phonecode' => '504'],
            'HU' => ['name' => 'Hungary', 'phonecode' => '36'],
            'IS' => ['name' => 'Iceland', 'phonecode' => '354'],
            'IN' => ['name' => 'India', 'phonecode' => '91'],
            'ID' => ['name' => 'Indonesia', 'phonecode' => '62'],
            'IQ' => ['name' => 'Iraq', 'phonecode' => '964'],
            'IE' => ['name' => 'Ireland', 'phonecode' => '353'],
            'IL' => ['name' => 'Israel', 'phonecode' => '972'],
            'IT' => ['name' => 'Italy', 'phonecode' => '39'],
            'JM' => ['name' => 'Jamaica', 'phonecode' => '1876'],
            'JP' => ['name' => 'Japan', 'phonecode' => '81'],
            'JO' => ['name' => 'Jordan', 'phonecode' => '962'],
            'KZ' => ['name' => 'Kazakhstan', 'phonecode' => '7'],
            'KE' => ['name' => 'Kenya', 'phonecode' => '254'],
            'KI' => ['name' => 'Kiribati', 'phonecode' => '686'],
            'KW' => ['name' => 'Kuwait', 'phonecode' => '965'],
            'KG' => ['name' => 'Kyrgyzstan', 'phonecode' => '996'],
            'LV' => ['name' => 'Latvia', 'phonecode' => '371'],
            'LB' => ['name' => 'Lebanon', 'phonecode' => '961'],
            'LS' => ['name' => 'Lesotho', 'phonecode' => '266'],
            'LR' => ['name' => 'Liberia', 'phonecode' => '231'],
            'LI' => ['name' => 'Liechtenstein', 'phonecode' => '423'],
            'LT' => ['name' => 'Lithuania', 'phonecode' => '370'],
            'LU' => ['name' => 'Luxembourg', 'phonecode' => '352'],
            'MG' => ['name' => 'Madagascar', 'phonecode' => '261'],
            'MW' => ['name' => 'Malawi', 'phonecode' => '265'],
            'MY' => ['name' => 'Malaysia', 'phonecode' => '60'],
            'MV' => ['name' => 'Maldives', 'phonecode' => '960'],
            'ML' => ['name' => 'Mali', 'phonecode' => '223'],
            'MT' => ['name' => 'Malta', 'phonecode' => '356'],
            'MQ' => ['name' => 'Martinique', 'phonecode' => '596'],
            'MR' => ['name' => 'Mauritania', 'phonecode' => '222'],
            'MU' => ['name' => 'Mauritius', 'phonecode' => '230'],
            'YT' => ['name' => 'Mayotte', 'phonecode' => '269'],
            'MX' => ['name' => 'Mexico', 'phonecode' => '52'],
            'MC' => ['name' => 'Monaco', 'phonecode' => '377'],
            'MN' => ['name' => 'Mongolia', 'phonecode' => '976'],
            'MA' => ['name' => 'Morocco', 'phonecode' => '212'],
            'MZ' => ['name' => 'Mozambique', 'phonecode' => '258'],
            'NA' => ['name' => 'Namibia', 'phonecode' => '264'],
            'NR' => ['name' => 'Nauru', 'phonecode' => '674'],
            'NP' => ['name' => 'Nepal', 'phonecode' => '977'],
            'NL' => ['name' => 'Netherlands', 'phonecode' => '31'],
            'AN' => ['name' => 'Netherlands Antilles', 'phonecode' => '599'],
            'NC' => ['name' => 'New Caledonia', 'phonecode' => '687'],
            'NZ' => ['name' => 'New Zealand', 'phonecode' => '64'],
            'NI' => ['name' => 'Nicaragua', 'phonecode' => '505'],
            'NE' => ['name' => 'Niger', 'phonecode' => '227'],
            'NG' => ['name' => 'Nigeria', 'phonecode' => '234'],
            'NO' => ['name' => 'Norway', 'phonecode' => '47'],
            'OM' => ['name' => 'Oman', 'phonecode' => '968'],
            'PK' => ['name' => 'Pakistan', 'phonecode' => '92'],
            'PA' => ['name' => 'Panama', 'phonecode' => '507'],
            'PG' => ['name' => 'Papua New Guinea', 'phonecode' => '675'],
            'PY' => ['name' => 'Paraguay', 'phonecode' => '595'],
            'PE' => ['name' => 'Peru', 'phonecode' => '51'],
            'PH' => ['name' => 'Philippines', 'phonecode' => '63'],
            'PL' => ['name' => 'Poland', 'phonecode' => '48'],
            'PT' => ['name' => 'Portugal', 'phonecode' => '351'],
            'QA' => ['name' => 'Qatar', 'phonecode' => '974'],
            'RE' => ['name' => 'Reunion', 'phonecode' => '262'],
            'RO' => ['name' => 'Romania', 'phonecode' => '40'],
            'RU' => ['name' => 'Russia', 'phonecode' => '7'],
            'RW' => ['name' => 'Rwanda', 'phonecode' => '250'],
            'LC' => ['name' => 'Saint Lucia', 'phonecode' => '1758'],
            'SM' => ['name' => 'San Marino', 'phonecode' => '378'],
            'ST' => ['name' => 'Sao Tome And Principe', 'phonecode' => '239'],
            'SA' => ['name' => 'Saudi Arabia', 'phonecode' => '966'],
            'SN' => ['name' => 'Senegal', 'phonecode' => '221'],
            'SC' => ['name' => 'Seychelles', 'phonecode' => '248'],
            'SL' => ['name' => 'Sierra Leone', 'phonecode' => '232'],
            'SG' => ['name' => 'Singapore', 'phonecode' => '65'],
            'SK' => ['name' => 'Slovakia', 'phonecode' => '421'],
            'SI' => ['name' => 'Slovenia', 'phonecode' => '386'],
            'SB' => ['name' => 'Solomon Islands', 'phonecode' => '677'],
            'SO' => ['name' => 'Somalia', 'phonecode' => '252'],
            'ZA' => ['name' => 'South Africa', 'phonecode' => '27'],
            'ES' => ['name' => 'Spain', 'phonecode' => '34'],
            'LK' => ['name' => 'Sri Lanka', 'phonecode' => '94'],
            'SD' => ['name' => 'Sudan', 'phonecode' => '249'],
            'SR' => ['name' => 'Suriname', 'phonecode' => '597'],
            'SZ' => ['name' => 'Swaziland', 'phonecode' => '268'],
            'SE' => ['name' => 'Sweden', 'phonecode' => '46'],
            'CH' => ['name' => 'Switzerland', 'phonecode' => '41'],
            'TJ' => ['name' => 'Tajikistan', 'phonecode' => '992'],
            'TH' => ['name' => 'Thailand', 'phonecode' => '66'],
            'TG' => ['name' => 'Togo', 'phonecode' => '228'],
            'TO' => ['name' => 'Tonga', 'phonecode' => '676'],
            'TT' => ['name' => 'Trinidad And Tobago', 'phonecode' => '1868'],
            'TN' => ['name' => 'Tunisia', 'phonecode' => '216'],
            'TR' => ['name' => 'Turkey', 'phonecode' => '90'],
            'TM' => ['name' => 'Turkmenistan', 'phonecode' => '7370'],
            'TC' => ['name' => 'Turks And Caicos Islands', 'phonecode' => '1649'],
            'TV' => ['name' => 'Tuvalu', 'phonecode' => '688'],
            'UG' => ['name' => 'Uganda', 'phonecode' => '256'],
            'UA' => ['name' => 'Ukraine', 'phonecode' => '380'],
            'AE' => ['name' => 'United Arab Emirates', 'phonecode' => '971'],
            'GB' => ['name' => 'United Kingdom', 'phonecode' => '44'],
            'US-AL' => ['name' => 'USA (Alabama)', 'phonecode' => '1'],
            'US-AK' => ['name' => 'USA (Alaska)', 'phonecode' => '1'],
            'US-AS' => ['name' => 'USA (American Samoa)', 'phonecode' => '1'],
            'US-AZ' => ['name' => 'USA (Arizona)', 'phonecode' => '1'],
            'US-AR' => ['name' => 'USA (Arkansas)', 'phonecode' => '1'],
            'US-CA' => ['name' => 'USA (California)', 'phonecode' => '1'],
            'US-CO' => ['name' => 'USA (Colorado)', 'phonecode' => '1'],
            'US-CT' => ['name' => 'USA (Connecticut)', 'phonecode' => '1'],
            'US-DE' => ['name' => 'USA (Delaware)', 'phonecode' => '1'],
            'US-DC' => ['name' => 'USA (District of Columbia)', 'phonecode' => '1'],
            'US-FM' => ['name' => 'USA (Federated States of Micronesia)', 'phonecode' => '1'],
            'US-FL' => ['name' => 'USA (Florida)', 'phonecode' => '1'],
            'US-GA' => ['name' => 'USA (Georgia)', 'phonecode' => '1'],
            'US-GU' => ['name' => 'USA (Guam)', 'phonecode' => '1'],
            'US-HI' => ['name' => 'USA (Hawaii)', 'phonecode' => '1'],
            'US-ID' => ['name' => 'USA (Idaho)', 'phonecode' => '1'],
            'US-IL' => ['name' => 'USA (Illinois)', 'phonecode' => '1'],
            'US-IN' => ['name' => 'USA (Indiana)', 'phonecode' => '1'],
            'US-IA' => ['name' => 'USA (Iowa)', 'phonecode' => '1'],
            'US-KS' => ['name' => 'USA (Kansas)', 'phonecode' => '1'],
            'US-KY' => ['name' => 'USA (Kentucky)', 'phonecode' => '1'],
            'US-LA' => ['name' => 'USA (Louisiana)', 'phonecode' => '1'],
            'US-ME' => ['name' => 'USA (Maine)', 'phonecode' => '1'],
            'US-MH' => ['name' => 'USA (Marshall Islands)', 'phonecode' => '1'],
            'US-MD' => ['name' => 'USA (Maryland)', 'phonecode' => '1'],
            'US-MA' => ['name' => 'USA (Massachusetts)', 'phonecode' => '1'],
            'US-MI' => ['name' => 'USA (Michigan)', 'phonecode' => '1'],
            'US-MN' => ['name' => 'USA (Minnesota)', 'phonecode' => '1'],
            'US-MS' => ['name' => 'USA (Mississippi)', 'phonecode' => '1'],
            'US-MO' => ['name' => 'USA (Missouri)', 'phonecode' => '1'],
            'US-MT' => ['name' => 'USA (Montana)', 'phonecode' => '1'],
            'US-NE' => ['name' => 'USA (Nebraska)', 'phonecode' => '1'],
            'US-NV' => ['name' => 'USA (Nevada)', 'phonecode' => '1'],
            'US-NH' => ['name' => 'USA (New Hampshire)', 'phonecode' => '1'],
            'US-NJ' => ['name' => 'USA (New Jersey)', 'phonecode' => '1'],
            'US-NM' => ['name' => 'USA (New Mexico)', 'phonecode' => '1'],
            'US-NY' => ['name' => 'USA (New York)', 'phonecode' => '1'],
            'US-NC' => ['name' => 'USA (North Carolina)', 'phonecode' => '1'],
            'US-ND' => ['name' => 'USA (North Dakota)', 'phonecode' => '1'],
            'US-MP' => ['name' => 'USA (Northern Mariana Islands)', 'phonecode' => '1'],
            'US-OH' => ['name' => 'USA (Ohio)', 'phonecode' => '1'],
            'US-OK' => ['name' => 'USA (Oklahoma)', 'phonecode' => '1'],
            'US-OR' => ['name' => 'USA (Oregon)', 'phonecode' => '1'],
            'US-PW' => ['name' => 'USA (Palau)', 'phonecode' => '1'],
            'US-PA' => ['name' => 'USA (Pennsylvania)', 'phonecode' => '1'],
            'US-PR' => ['name' => 'USA (Puerto Rico)', 'phonecode' => '1'],
            'US-RI' => ['name' => 'USA (Rhode Island)', 'phonecode' => '1'],
            'US-SC' => ['name' => 'USA (South Carolina)', 'phonecode' => '1'],
            'US-SD' => ['name' => 'USA (South Dakota)', 'phonecode' => '1'],
            'US-TN' => ['name' => 'USA (Tennessee)', 'phonecode' => '1'],
            'US-TX' => ['name' => 'USA (Texas)', 'phonecode' => '1'],
            'US-UT' => ['name' => 'USA (Utah)', 'phonecode' => '1'],
            'US-VT' => ['name' => 'USA (Vermont)', 'phonecode' => '1'],
            'US-VI' => ['name' => 'USA (Virgin Islands)', 'phonecode' => '1'],
            'US-VA' => ['name' => 'USA (Virginia)', 'phonecode' => '1'],
            'US-WA' => ['name' => 'USA (Washington)', 'phonecode' => '1'],
            'US-WV' => ['name' => 'USA (West Virginia)', 'phonecode' => '1'],
            'US-WI' => ['name' => 'USA (Wisconsin)', 'phonecode' => '1'],
            'US-WY' => ['name' => 'USA (Wyoming)', 'phonecode' => '1'],
            'US-AE' => ['name' => 'USA (Armed Forces Europe, the Middle East, and Canada)', 'phonecode' => '1'],
            'US-AP' => ['name' => 'USA (Armed Forces Pacific)', 'phonecode' => '1'],
            'US-AA' => ['name' => 'USA (Armed Forces Americas)', 'phonecode' => '1'],

            'UY' => ['name' => 'Uruguay', 'phonecode' => '598'],
            'UZ' => ['name' => 'Uzbekistan', 'phonecode' => '998'],
            'VU' => ['name' => 'Vanuatu', 'phonecode' => '678'],
            'VE' => ['name' => 'Venezuela', 'phonecode' => '58'],
            'EH' => ['name' => 'Western Sahara', 'phonecode' => '212'],
            'YE' => ['name' => 'Yemen', 'phonecode' => '967'],
            'ZM' => ['name' => 'Zambia', 'phonecode' => '260'],
            'ZW' => ['name' => 'Zimbabwe', 'phonecode' => '263'],
        ];
        return array_map(function ($v) use ($return) {
            return $v[$return] ?? $v;
        }, $result);
    }
}