version : '3'
services :
  php :
    image: yiisoftware/yii2-php:7.4-fpm-23.2.0-nginx
    volumes :
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports :
      - '8000:80'
    links :
      - mariadb
  mariadb :
    image : mariadb:10.1
    volumes :
      - mariadb:/var/lib/mysql
    environment :
      MYSQL_ALLOW_EMPTY_PASSWORD : " no"
      MYSQL_ROOT_PASSWORD : "root"
      MYSQL_USER : 'root'
      MYSQL_PASSWORD : 'root'
      MYSQL_DATABASE : 'yii2_project'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes :
  mariadb: