###############################################################################
#                          Generated on docker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine

    mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "8091:8025"

    mysql:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=yii2_project
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8092:3306"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx:/var/log/nginx
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8090:80"

    php-fpm:
      build: docker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        #- ./docker/php-fpm/php-fpm-startup:/usr/bin/php-fpm
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        - ./docker/php-fpm/xdebug.ini:/etc/php/7.3/mods-available/xdebug.ini
        #- ./docker/php-fpm/cronjobs /etc/cron.d/php-app-cronjob