<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Brief' => '',
    'Categories' => '',
    'Category ID' => '',
    'Category list' => '',
    'Content' => '',
    'Could not delete item.' => '',
    'Create' => '',
    'Create Category' => '',
    'Create Item' => '',
    'Create {modelClass}' => '',
    'Created At' => '',
    'Delete' => '',
    'Depth' => '',
    'File delete error' => '',
    'File rename error' => '',
    'File successfully deleted' => '',
    'File successfully renamed' => '',
    'ID' => '',
    'Image' => '',
    'Is Active' => '',
    'Item ID' => '',
    'Items' => '',
    'Lft' => '',
    'Name' => '',
    'No' => '',
    'Reset' => '',
    'Rgt' => '',
    'Root category can not be deleted.' => '',
    'Search' => '',
    'Select categories' => '',
    'Settings' => '',
    'Successfully created.' => '',
    'Successfully deleted.' => '',
    'Successfully updated.' => '',
    'Title' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'User ID' => '',
    'Yes' => '',
];
