<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Rules' => '',
    'Auth item childs' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Created at' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'Name' => '',
    'Permission' => '',
    'Permissions' => '',
    'Reset' => '',
    'Role' => '',
    'Role saved' => '',
    'Rule full class name' => '',
    'Rule name' => '',
    'Saved' => '',
    'Search' => '',
    'Settings' => '',
    'Type' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated at' => '',
    'User ID' => '',
    'Users' => '',
    'default_role_delete_error' => '',
    'default_role_renaming_error' => '',
    'only_root_remove_denied' => '',
    'permission' => '',
    'role' => '',
    'role_default' => '',
    'role_guest' => '',
    'role_root' => '',
    'title_roles' => '',
    'title_roles_to_managers' => '',
];
